name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      ambiente: test
      proyecto: training

    runs-on: ubuntu-latest

    steps:
      - name: "Mensaje simple"
        run: echo "Esto es un mensaje para la training"

      - name: "Mensaje con variable y multiple linea"
        if: ${{env.ambiente == 'test'}}
        run: |
          echo "ambiente: ${{env.ambiente}}"
          echo "proyecto: ${{env.proyecto}}"